substitutions:
  host_name: kitchen-cover
  node_name: Kitchen Cover
  input: swapped
  output: swapped

packages:
  cover: !include common/shelly-2.5-cover.yaml

wifi:
  manual_ip:
    static_ip: 192.168.178.19
    gateway: 192.168.178.1
    subnet: 255.255.255.0
