substitutions:
  host_name: lab-cover
  node_name: Lab Cover

packages:
  cover: !include common/shelly-2.5-cover.yaml

wifi:
  manual_ip:
    static_ip: 192.168.178.16
    gateway: 192.168.178.1
    subnet: 255.255.255.0
