substitutions:
  host_name: studio-cover
  node_name: Studio Cover

packages:
  cover: !include common/shelly-2.5-cover.yaml

wifi:
  manual_ip:
    static_ip: 192.168.178.15
    gateway: 192.168.178.1
    subnet: 255.255.255.0
