packages:
  cover: !include
    file: common/shelly-2.5-cover.yaml
    vars:
      host_name: studio-cover
      node_name: Studio Cover
      static_ip: 192.168.178.15
      subnet: 255.255.255.0
      gateway: 192.168.178.1
      input: swapped
      log_level: DEBUG
  reboot_at_night: !include common/reboot-at-night.yaml
  debug: !include common/debug.yaml

binary_sensor:
  - platform: gpio_monitor
    name: gpio_monitor
    pin: GPIO10
