# Required Variables
#  * node_name: The name of this node. For example: "My Device"
#  * host_name: Adaptation of the node_name to follow DNS rules. For example: "my-device"

esphome:
  name: ${host_name}

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${host_name}-portal"
    password: !secret ap_password 

captive_portal:

sensor:
  - platform: uptime
    name: ${node_name} Uptime
    update_interval: 60s

  - platform: wifi_signal
    name: "${node_name} WiFi Signal dB"
    update_interval: 60s

button:
  - platform: restart
    name: "${node_name} Reboot"
