# Required Variables
#  * node_name: The name of this node. For example: "My Device"
#  * host_name: Adaptation of the node_name to follow DNS rules. For example: "my-device"

defaults:
  # Log level default value is INFO.
  log_level: INFO
  # Should the open input be inverted
  invert_input: "false"

packages:
  plat: !include
    file: esp8266.yaml
    vars:
      host_name: ${host_name}
      node_name: ${node_name}
      log_level: ${log_level}
      restore_from_flash: true
  base: !include ha.yaml

binary_sensor:
  - platform: gpio
    id: the_switch
    internal: true
    pin:
      number: GPIO5
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_state:
      then:
        - light.toggle: the_light

light:
  - platform: binary
    name: Studio Light
    output: the_relay
    id: the_light
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: gpio
    pin: GPIO4
    id: the_relay

