substitutions:
  # Should the open input be inverted
  invert_input: "false"

packages:
  base: !include base.yaml

esp8266:
  board: esp01_1m

logger:
  hardware_uart: UART0

binary_sensor:
  - platform: gpio
    id: the_switch
    internal: true
    pin:
      number: GPIO5
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_state:
      then:
        - light.toggle: the_light

light:
  - platform: binary
    name: Studio Light
    output: the_relay
    id: the_light

output:
  - platform: gpio
    pin: GPIO4
    id: the_relay

